spawn:
  x: 0.5
  y: 100
  z: 0.5
portal:
  pos1:
    x: 10
    z: 10
  pos2:
    x: 10
    z: 10
npcs:
  donator:
    world: "world"
    x: 16.5
    y: 110
    z: 16.5
    yaw: 0
    pitch: 0
  voter:
    world: "world"
    x: -16.5
    y: 110
    z: 16.5
    yaw: 0
    pitch: 0
scoreboards:
  normal:
    title: "&5&lColonyMC &7[Lobby]"
    lines:
      - '&f&m-+--------------+-'
      - ' '
      - '&5&lPlayer Info:'
      - '&5» &fRank: &d%vault_group%'
      - '&5» &fPing: &d%player_ping%ms'
      - ' '
      - '&5&lServer Info:'
      - '&5» &fSkyblock: &cMaintenance'
      - '&5» &f&kOOOOOOO&r: &cOfflineeeee'
      - '&5» &f&kOOOOOOO&r: &cOffline'
      - '&5» &dplay.colonymc.net'
      - '&f&m-+--------------+-'
    updating_lines:
      - 3
      - 4
      - 7
      - 8
      - 9
  battlebox:
    title: "&5&lColonyMC &7[BattleBox]"
    lines:
      - '&f&m-+--------------+-'
      - ' '
      - '&5» &fStatus: %battlebox_status%'
      - ' '
      - '&5&lTime left:'
      - '&5» %time_left%'
      - ' '
      - '&5» &fYour points: %battlebox_points_own%'
      - '&5» &fYour kills: %battlebox_kills_own%'
      - ''
      - '&5» &fTheir points: %battlebox_points_enemy%'
      - '&5» &fOpponents left: %battlebox_enemies_left%'
      - ''
      - '&5» &dplay.colonymc.net'
      - '&f&m-+--------------+-'
    updating_lines:
      - 2
      - 5
      - 7
      - 8
      - 10
      - 11