name: ColonyHubCore
version: 1.0
author: ACrispyCookie
depends: [Citizens, PlaceholderAPI, ColonySpigotAPI, ColonyAPI]
main: net.colonymc.colonyhubcore.Main
commands:
  message:
    description: Command used to send private messages.
    aliases: [msg, t, pm]
  reply:
    description: Command used to reply to a conversation.
    aliases: [r]
  battlebox:
    description: Command to manage BattleBox
  pvpmode:
    description: Command to toggle a player's pvp mode.
  setupplayer:
    description: Command to reset a player on the lobby.
  spawn:
    description: Command to teleport to the spawn.
  server:
    description: Command to open the server selector.
  help:
    description: Command to open the commands menu.
  menu:
    description: Command to open the helpful menu.
  buildermode:
    description: Command to enter the builder mode.
  kaboom:
    description: Explosive command!
  cookie:
    description: Use it if you are hungry!
  plugin:
    description: Plugin info.
  about:
    description: Plugin info.